<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>Nexora.RAMFlow.App</RootNamespace>
    <AssemblyName>Nexora.RAMFlow</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nexora.RAMFlow.Core\Nexora.RAMFlow.Core.csproj" />
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>
</Project>
